[project]
name = "weather-api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "argparse>=1.4.0",
    "pytest>=9.0.2",
    "requests>=2.32.5",
]

[tool.ruff]
line-length = 100
